### ISSUE TITLE
Redundant Debug Logging for ExecSync

### ISSUE THREAD

**Issue by pbcahill** [microsoft/azure-pipelines-task-lib#1069]
### Environment
azure-pipelines-task-lib version: 4.17.2

### Issue Description

Whenever using the `execSync` function, and have system.debug enabled for the pipeline run, every piece of the command being output as a separate debug line twice:

![{1AA92E14-9AFE-49B9-AEA4-8EC63D142470}](https://github.com/user-attachments/assets/39435e8a-b742-45b2-bc4f-7d330f028352)

That is the result from using `execSync` to run a curl command:
![{54205DC6-AB3A-4680-9A92-6D0C3CF5BA08}](https://github.com/user-attachments/assets/5a8c8601-a024-47eb-bf1d-f3d6efd77e39)

### Expected behaviour

I would expect whatever command is being executed to be debug logged on a single line. Also none of the debug lines should be duplicated. 

Would also be nice to have an option for `execSync` to not debug log the command at all. The existing `silent` option only masks the regular console output.

### Actual behaviour

Each piece or argument of the command is output on a new debug line and duplicated. No way to alter this behavior or mask.

**Comment by ivanduplenskikh** [comment]
@pbcahill, appreciate the alert. I'll review the matter and respond promptly.

**Comment by ivanduplenskikh** [comment]
@pbcahill, I successfully replicated the problem using a custom **script** task that make a request to a URL via the **curl** utility.
The core of this problem lies is how CmdLine/Bash/Powershell tasks are designed.
They utilize a tool wrapper which add listener for debug output. Then they subsequently invoke call exec method, which does the same action.

**CmdLineV2**: 
[tool listener](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/CmdLineV2/cmdline.ts#L39)
[exec listener](https://github.com/microsoft/azure-pipelines-tasks/blob/4defd17384f5e4cfaabfd1bb9537b13bb146c7d5/Tasks/CmdLineV2/cmdline.ts#L67)

**BashV3**:
[tool listener](https://github.com/microsoft/azure-pipelines-tasks/blob/4defd17384f5e4cfaabfd1bb9537b13bb146c7d5/Tasks/BashV3/bash.ts#L12)
[exec listener](https://github.com/microsoft/azure-pipelines-tasks/blob/4defd17384f5e4cfaabfd1bb9537b13bb146c7d5/Tasks/BashV3/bash.ts#L23)

**PowershellV2**:
[tool listener](https://github.com/microsoft/azure-pipelines-tasks/blob/4defd17384f5e4cfaabfd1bb9537b13bb146c7d5/Tasks/PowerShellV2/powershell.ts#L148)
[exec listener](https://github.com/microsoft/azure-pipelines-tasks/blob/4defd17384f5e4cfaabfd1bb9537b13bb146c7d5/Tasks/PowerShellV2/powershell.ts#L173)

Both these wrappers add listeners
[tool](https://github.com/microsoft/azure-pipelines-task-lib/blob/a56dfecac46753540e79da0d2c93fb41666c0c3e/node/task.ts#L1596)
[exec](https://github.com/microsoft/azure-pipelines-task-lib/blob/a56dfecac46753540e79da0d2c93fb41666c0c3e/node/task.ts#L1544)

Additionally, I'd like to point out that the 'silently' property does not impact the debug output.

**Comment by KonstantinTyukalov** [comment]
@pbcahill thanks for pointing this out! It's fixed in newest patch, `4.17.3`
I'm closing this bug, please let me know if you have any further questions.

**Comment by pbcahill** [comment]
Thank you @KonstantinTyukalov and @ivanduplenskikh for the very prompt responses and resolutions! I have tested the new version in my extensions and the duplicate debug log lines are no more.

**Comment by acheng-01** [comment]
@localconst @ivanduplenskikh I am seeing these debug messages while I'm on 5.2.1, without having set `TASK_TEST_TRACE=1` in the environment. Is there a way that I can get rid of them?
