### ISSUE TITLE
Hard to intercept output when redirecting StdErr

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/azure-pipelines-task-lib#183]
I tried to execute an executable (`tfx`) and in case of an error capture the error message. This turns out to be very difficult.

```
let tr = new tr.ToolRunner(tl.which("tfx.cmd"));
tr.exec(<any>{ failOnStdErr: false, errStream: myStream });
```

Doesn't redirect anything to `myStream`, it turns out thet when failOnStderr is `false` output is instead redirected to StdOut. 

But when I capture stdOut, the error message isn't added to my buffer:

```
let tr = new tr.ToolRunner(tl.which("tfx.cmd"));
tr.exec(<any>{ failOnStdErr: false, outStream: myStream });
```

Turns out this may have to do with the fact that I did't set IgnoreResultCode: false, because if that's set, it will fail the task before actually allowing me to inspect the result.

I looked at the ANT task and stole 

https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/ANT/anttask.ts#L241-L253

But that doesn't seem to work, it doesn't ever receive a line.

I simplified the code and removed the buffer (I get why it's there, but it isn't working it seems) and ended up with:

```
var buffer;
    tfx.on('stderr', function (data) {
        if (data) {
            var line =  data.toString();
            if (line.indexOf("Error:") >= 0) {
                var tferrorIndex = line.indexOf("TF1590010");
                if (tferrorIndex < 0) {
                    tl.setResult(tl.TaskResult.Failed, line);
                }
                else {
                    console.log(line.substring(tferrorIndex + 11));
                }
            }
        }
    });
    var result = tfx.exec({ silent: true, failOnStdErr: false });
```

and after a lot of frustration I finally found a way to (so far) reliably intercept the error output and override it.

All in all it took way too much time and I encountered too many surprises. 

My expectations would have been:

 * If I supply a error stream, it is called regardless of silent:true and failOnstdErr:false
 * If I set failOnStdErr:true, I expect the task to fail, but still allow me to intercept the output
 * If stdErr is redirected to stdOut by your code, I expect the output to end up in the supplied outStream, right now it bypasses the supplied outStream and is logged to the console.

**Comment by jessehouwing** [comment]
Found another way which seems to be the easiest:

```
    const result = tfx.execSync(<any>{ silent: false, failOnStdErr: false });
    if (result.stderr.search("error: Error: (?!.*TF1590010)") >= 0) {
        tl.setResult(tl.TaskResult.Failed, "Failed");
    } else {
        tl.setResult(tl.TaskResult.Succeeded, "Succeeded");
    }
```

It doesn't let me intercept the message (so I can remove the "ERROR:" part from it, but at least I get to inspect what I want.

**Comment by ericsciple** [comment]
tool runner emits stderr and stdout events that can be listened to.

also, it seems like it may be better for the lib to write to whatever stream it was given. that would give the user the flexibility to use the same stream if they want. the only thing that concerns me, i'm not sure offhand whether that would introduce any challenges due to stdout buffering.

**Comment by jessehouwing** [comment]
I've had very inconsistent results with the events as well, especially
since they act on buffers and not on lines. Plus they seem to influence the
standard behavior.

**Comment by damccorm** [comment]
Obviously this issue has been alive for a while, so some of the things you initially noted may have changed, my answer is based on the current version of the library:

> If I supply a error stream, it is called regardless of silent:true and failOnStdErr:false

I don't think it makes sense to send the error stream to stdErr (or an errStream that is supplied in place of stderr), this is discussed in more detail in #333. In short, if we don't want to failOnStdErr, then the error in the execution of a tool probably shouldn't be considered an error in the execution of an entire task.

> If I set failOnStdErr:true, I expect the task to fail, but still allow me to intercept the output
>If stdErr is redirected to stdOut by your code, I expect the output to end up in the supplied outStream, right now it bypasses the supplied outStream and is logged to the console.

I think this currently is the behavior - see [here](https://github.com/Microsoft/azure-pipelines-task-lib/blob/7dca1fc53e9886ac719a98e811b28339de108de0/node/toolrunner.ts#L727)

> I've had very inconsistent results with the events as well, especially since they act on buffers and not on lines. Plus they seem to influence the standard behavior.

I haven't run into this (maybe something that has been fixed since this was opened). Is this still an issue?

**Comment by damccorm** [comment]
I'm going to close here, please reopen if appropriate.
