### ISSUE TITLE
IExecOptions.silent = true causes MockTestRunner to return 0 executions.

### ISSUE THREAD

**Issue by ILMTitan** [Microsoft/azure-pipelines-task-lib#212]
If you run a command with `IExecOptions.silent = true`, the `MockTestRunner` will not think the tool has run. This is because the `MockToolRunner` swallows the `[command]` string with the silent option set. Even if it does not send to whole command to the output, `MockToolRunner` should still send `[command]` so it can be counted.

**Comment by damccorm** [comment]
@ILMTitan is this still causing issues for you? Per #418 we're not going to emit `[command]` because that's inconsistent with the actual behavior we would provide. Given that there's not a fantastic way to get this back from the child process without touching io and since it doesn't seem that unreasonable that a silent execution would be unmonitored, I'm tempted to just call this a no-op **if its not causing issues**.

**Comment by ILMTitan** [comment]
I am no longer working on the project that prompted this. If I recall, I ended up not using the MockToolRunner and instead did dependency injection, mocking the whole task-lib.
