### ISSUE TITLE
A function which returns whether it is running in Build or Release definition

### ISSUE THREAD

**Issue by mortezag** [Microsoft/azure-pipelines-task-lib#256]
Could you add a function which returns whether the task in running in Build or Release definition?

[Related issue in vsts-tasks repo](https://github.com/Microsoft/vsts-tasks/issues/4568 )

**Comment by ericsciple** [comment]
the workaround right now (solution?) is check the `system.hostType` variable

**Comment by mortezag** [comment]
Thanks Eric. I have already followed the workaround/solution you mentioned in the other thread, and it works for me. I am creating this issue per bryanmacfarlane suggestion.

**Comment by mmajcica** [comment]
@ericsciple would this be interestingly implementing for both PS an JS SDK? I find way more expressive at example calling a self-describing cmdlet instead of checking the content on a "cryptic" variable then acting based on the result.
I'll be happy to give it a try for both PS and JS and write the necessary tests. However the most difficult part, one or two cmdlets and naming of those, e.g. Test-IsBuild Test-IsRelease? Suggestions are welcome.

**Comment by ericsciple** [comment]
I would rather eliminate the need for task authors to take a different code path. What's the scenario?

**Comment by mmajcica** [comment]
One simple example, I wrote a task that can add tags to build and release.  My code path then needs to differentiate in between the two.
Considering different paths and variables available, sometimes in my tasks, I need to calculate values or initialize defaults that are different in between for build or release.

**Comment by damccorm** [comment]
Adding a function here feels redundant to me - it would just return the value of system.hostType - so I'm going to close. Feel free to reopen as appropriate.
