### ISSUE TITLE
Demands : ask for Node || Node.js

### ISSUE THREAD

**Issue by sandorfr** [Microsoft/azure-pipelines-task-lib#351]
Currently, the Node tool installers satisfies the `Node` demand. The vsts hosted agent provide the `Node.Js` Capability. 

I have  task (`Yarn`) which requires node js to run. Both are acceptable to run the task. How can I specify that. 

I'm afraid that at the moment the only thing I can do is remove the demands entirely and rely on the user to do the right thing.

**Comment by damccorm** [comment]
I don't think we currently support || statements in demands (or an equivalent feature). This could be a good enhancement though.

**Comment by damccorm** [comment]
@bryanmacfarlane my understanding is that their question is about having a demand that requires either node **or** node.js.

So basically what they want is something in the task.json like:
```demands=["Node" || "Node.js"]```
This could be satisfied by a tool that has ```satisfies=["Node"]``` or ```satisfies=["Node.js"]```

 It doesn't totally make sense to me why they'd need it for this particular case since there's not really a distinction between the 2 - I guess both names are in use for some reason and that's keeping the node demand from being satisfied when the other task provides node.js - but I can imagine a situation where it could be useful to specify ```demands=["A" || "B"]```

@sandorfr is this correct?

**Comment by sandorfr** [comment]
@damccorm you are perfectly right.

The problem we have is that there’s a mismatch between the default node capability that comes with the preinstalled node on hosted agent and what the node installer satisfies. On is using Node and the other one Node.Js

Maybe the easiest way to solve that would be for the installer to actually satisfy both Node and Node.js demands

**Comment by damccorm** [comment]
Yeah, that's true. As I think about it, that should probably be our recommendation here and it makes this enhancement unnecessary. I'm going to close here, @sandorfr could you create an issue for this in the task lib?
