### ISSUE TITLE
Verify environment variable values set by task from unit test

### ISSUE THREAD

**Issue by charleszipp** [microsoft/azure-pipelines-task-lib#472]
I am working on a task that executes a tool. This tool requires a few environment variables be set prior to running the tool. In my test i want to be sure that these environment variables are set to the expected value. If they were not set appropriately the task would fail to execute. 

Is there a way to do this? Example of the code within my task under test.

```javascript
// todo: verify this is set to the value i provided for tenantid.
process.env['ARM_TENANT_ID'] = tasks.getEndpointAuthorizationParameter(command.environmentServiceName, "tenantid", false);
```

I have tried examining `process.env` but, the variables are not set on this. It appears child_process.spawn/spawnSync clones `process.env` before executing the child process. Therefore, it does not have the vars set by the actual task (only the ones set on `process.env` prior to spawning the child process).

**Comment by damccorm** [comment]
Yeah, that is intentional behavior so that execution of one task can't set environment variables that could potentially mess up other tasks, it does make testing that specific functionality challenging though - I don't think we really have a way of doing this. My recommendation here would be to check in your actual task code if this is being set and instantly failing out (or warning as appropriate) if it hasn't been set. This kinda feels like what you should be doing anyways if I'm understanding the situation correctly, it would allow you to provide meaningful feedback as to why you failed instead of passing that responsibility on to the tool. Then for your test you could both test not setting that/failing and setting it/succeeding.

**Comment by charleszipp** [comment]
@damccorm The tool im executing that needs these env's set is terraform executable. I do not have control to add validation to the terraform executable. If you were suggesting i instead add these in my task code that executes the terraform executable this also does not seem like a good solution. The reason is because my task code is setting these env's on behalf of the user based on what they provided into a required service endpoint. So with what you suggested, i would execute my code that translates the service endpoint into required env vars for the terraform executable then, validate those env's exist? This doesnt seem like an effective way to enforce the contract that exists between my task code and the terraform tool. Normally i would do that with a unit test external to the task code.

If it were a matter of validating input, i would agree with your suggestion but, im trying to assert that the contract that exists between the pipeline task and the terraform executable is maintained as code changes are made. This contract is in the form of translating required input to env vars the tool needs to successfully execute.

Let me know your thoughts or suggestions given that information.

**Comment by damccorm** [comment]
Ah, sorry I misread your initial comment and thought it was user input. So to make sure I understand correctly:
1. You are setting process.env['ARM_TENANT_ID'] (and other environment variables)
2. The tool you are running needs this to be set in order to execute correctly
3. You want to make sure the environment variables were correctly set, regardless of code path/changes in the code

That seems like a reasonable thing to want to do. Unfortunately, I don't see a great solution to this since environment variables aren't persisted between tasks (and I don't think we want them to be). One (non-optimal) solution would be to pull the exec call out into a separate function which can be mocked. You could check the environment variables there.

I think it would definitely be good to have a better solution, I need to think a bit more about what that would look like though, I think there's a good chance it would be best suited for our upcoming major version revision.

**Comment by charleszipp** [comment]
You got it @damccorm. I look forward to seeing the solution you come up with in the next major revision.

**Comment by damccorm** [comment]
@charleszipp sorry this has taken a bit - I'm taking another look at this as we major version. As I think more about this, though, I think the simplest solution might be to just write a debug statement with the value of the environment variables. Then you can check the stdout of the task to make sure it was written correctly.

This also just feels like the right thing to do for debugging errors. Does that seem reasonable? Otherwise we need to do something like capturing the environment and somehow pass it out of the child process - there doesn't seem to me to be a clean way of doing this.

**Comment by damccorm** [comment]
Closing since I think this is a no-op on our end
