### ISSUE TITLE
_loadLocStrings runs into an infinite loop

### ISSUE THREAD

**Issue by shudv** [Microsoft/azure-pipelines-task-lib#482]
I am using webpack@4.37.1 to package my task dependencies and I am running into an infinite loop when I am trying to run the task locally. 

Most likely it's a faulty configuration on my side but even then the library should not run into infinite loops. I have attached relevant images. 

![image](https://user-images.githubusercontent.com/6473147/49920048-d41a1f80-fece-11e8-9e7a-ee54e0190427.png)

![image](https://user-images.githubusercontent.com/6473147/49920114-09267200-fecf-11e8-847f-0735f257c946.png)

**Comment by damccorm** [comment]
Hm, I haven't seen anything like that before - do you know what call is triggering the loop?

**Comment by shudv** [comment]
This library contains a lib.json and localisation string files which do not get automatically packed using webpack. Unfortunately, in the absence of these files, the _loadLocStrings runs into an infinite loop. 

Even after I manually copied those files to my packaging folder, I can't get this to work.

**Comment by shudv** [comment]
This error can be easily reproduced by using following webpack config

`module.exports = env => {
    return {
        target: "node",
        entry: "./src/main.ts",
        output: {
            filename: "main.js",
            path: path.resolve(__dirname, "./../dist"),
            publicPath: '/'
        },
        optimization: {
            minimize: false,
        },
        resolve: {
            modules: ["node_modules"],
            extensions: [ ".ts", ".js" ]
        },
        module: {
            rules: [
                {
                    test: /\.ts?$/,
                    exclude: /node_modules/,
                    enforce: "pre",
                    use: [ "ts-loader", "tslint-loader" ]
                }
            ]
        },
        devtool: "source-map",
        node: {
            fs: 'empty',
            child_process: 'empty'
        }
    };
};
`

**Comment by damccorm** [comment]
Ah, I see, if [_loc](https://github.com/Microsoft/azure-pipelines-task-lib/blob/b9602e028255065aed92c64fa5c07f235542b1bc/node/internal.ts#L181) is called for the first time, it calls [_loadLocStrings](https://github.com/Microsoft/azure-pipelines-task-lib/blob/b9602e028255065aed92c64fa5c07f235542b1bc/node/internal.ts#L185). This normally makes sense, but if [_exist(resourceFile)](https://github.com/Microsoft/azure-pipelines-task-lib/blob/b9602e028255065aed92c64fa5c07f235542b1bc/node/internal.ts#L102) returns false, we [call _loc](https://github.com/Microsoft/azure-pipelines-task-lib/blob/b9602e028255065aed92c64fa5c07f235542b1bc/node/internal.ts#L135) again which kicks off the loop. I think to fix this we can probably just set ```_libResourceFileLoaded = true``` before [this call](https://github.com/Microsoft/azure-pipelines-task-lib/blob/b9602e028255065aed92c64fa5c07f235542b1bc/node/internal.ts#L135), I'll go ahead and create a PR for this.

**Comment by JiriKovar** [comment]
We're running into the same issue and it seems that the whole package is not really suited for webpack because of similar problems. Can you tell us when will the next version be released and whether you plan to address these problems with webpack? Thanks.

**Comment by shudv** [comment]
@JiriKovar I was able to resolve the issue using the following hack. Instead of *webpack requiring* the resource file just normally require it instead-

```
// This replacement is required to allow azure-pipelines-task-lib to load the 
// json resource file correctly
{
    dir: "dist/custom-task",
    files: ["main.js"],
    rules: [{
        search: /__webpack_require__\(.*\)\(resourceFile\)/,
        replace: 'require(resourceFile)'
    }]
},
```

Let me know if it works. I have also published a working version of the full webpack config for a custom pipeline task as a template [here](https://github.com/shudv/azure-pipelines-task-template/blob/master/webpack.config.js), in case you need it.

**Comment by damccorm** [comment]
Yeah, this is known - webpack won't work right out of the box because we have dynamic dependencies on localization files. I don't know of a great way around that right now, and don't think that its super vital in the short term (tasks tend to not be super large) - if I'm overlooking something and webpack really is a must let me know, but regardless this is something I had on my mind to address eventually.

**Comment by JiriKovar** [comment]
@damccorm we used to have to split our packages per 2-3 tasks max, because we were hitting the maximum package size due to node_modules being everywhere (currently we are managing 21 custom tasks as the seem like the best way to extend Azure DevOps), but the main problem was sharing code between them - we had 2 options:

1. some proprietary script (gulp) that would copy files from upper directories and replace requires
2. webpack

And honestly, I would consider webpack a standard solution for this problem these days, so the support would be really appreciated. Anyway, hearing that the only known issue are with the localization files (which we don't use except the inbuilt lib.json) is somewhat reassuring.

@shudv It works, thanks a lot!
