### ISSUE TITLE
findMatch not working when pattern has a trailing slash

### ISSUE THREAD

**Issue by joshmgross** [Microsoft/azure-pipelines-task-lib#491]
Users are reporting here (https://github.com/Microsoft/azure-pipelines-tasks/issues/9389#issuecomment-458553194) that the `PublishCodeCoverage` task doesn't work when the `ReportingDirectory` contains a trailing slash. 

This bug started from my change here (https://github.com/Microsoft/azure-pipelines-tasks/commit/7807be3c01741a46db528a35f719a66789b832fe) that passes all file paths into `findMatch`.

Is this intentional behavior? Should the `PublishCodeCoverage` task just remove trailing slashes?

**Comment by damccorm** [comment]
I think we should be able to handle trailing slashes. I'm struggling to reproduce though - I created [this test case](https://github.com/Microsoft/azure-pipelines-task-lib/blob/2dc3b16c8c32f7ba2622ca10b782967f5db49bad/node/test/findmatchtests.ts#L462) and queued [this build](https://dev.azure.com/mseng/PipelineTools/_build/results?buildId=8340255) against it.

Ignoring the failing PowerShell tests (which also probably need to be looked into), the new test that I added isn't failing. Are you sure that's what's causing the issue, and if so could you try to get a little more detail on when its failing on your end?

**Comment by joshmgross** [comment]
@damccorm Thanks for testing it, I was also struggling to get a repro. The trailing slash is just based off what the customers are posting. I'll look into it a bit more.

**Comment by joshmgross** [comment]
@damccorm I was mistaken, the issue occurs when the `pattern` contains a trailing slash. The task is using `findMatch` to resolve wildcards and find a directory.

I modified your test and was able to repro:

```
    it('supports trailing slash', (done: MochaDone) => {
        this.timeout(1000);

        let root: string = path.join(testutil.getTestTemp(), 'find-and-match_supports-trailing-slash');
        tl.mkdirP(path.join(root));
        tl.mkdirP(path.join(root, "subDirectory"))
        let patterns: string[] = [
            'subDirectory/',
        ];
        let actual: string[] = tl.findMatch(path.join(root) + '/', patterns, <tl.FindOptions>{ followSymbolicLinks: false, followSpecifiedSymbolicLink: false }, <tl.MatchOptions>{ matchBase: true });
        let expected: string[] = [
            path.join(root, 'subDirectory')
        ];
        assert.deepEqual(actual, expected.sort());

        done();
    });
```

`findMatch` fails to find the directory `subDirectory` becasue the patten ends in a trailing slash.

Is this a bug? Or are we misusing `findMatch` in our task on paths instead of files.

**Comment by damccorm** [comment]
You can definitely use ```findMatch``` on paths like you're trying to do ([this test](https://github.com/Microsoft/azure-pipelines-task-lib/blob/2dc3b16c8c32f7ba2622ca10b782967f5db49bad/node/test/findmatchtests.ts#L429) is an example of exactly this).

I do think that it being a trailing slash in the pattern changes the question of whether this is a bug though. I'm inclined to say this is just expected behavior for a couple reasons:
1) Its not immediately clear to me that we should be matching here. I could go either way, though I'd probably lean towards matching it if all things were equal. It doesn't, however, feel worth breaking back-compat and/or releasing a new major version for this.
2) I believe this discrepancy is arising from a call to [```minimatch.match```](https://github.com/Microsoft/azure-pipelines-task-lib/blob/fa4a786d9fc9f1a962c085a362065bd1eda182fa/node/task.ts#L1570). I tend to trust them as a source of what _should_ be done. Whether its right or not, its probably not outside of the expectations of a typical JS developer.
3) Because its arising from the ```minimatch``` call, fixing it would require writing the logic from scratch or logging an issue with them. I don't feel like I can confidently articulate _why_ this is a bug, so it doesn't feel like the first option is worth the pain/potential for new bugs and I don't think I could make a compelling argument for the second option.

If you disagree I'm open to further conversation here, but as it stands I'm more inclined to call it expected behavior and say its the user's responsibility to remove trailing slashes.

**Comment by joshmgross** [comment]
@damccorm Thanks, I agree with your call. I'll close this issue.
