### ISSUE TITLE
How do I download tools and respect agent proxy configuration?

### ISSUE THREAD

**Issue by charleszipp** [Microsoft/azure-pipelines-task-lib#508]
### Issue Description
I had an [issue opened on my repo](https://github.com/charleszipp/azure-pipelines-tasks-terraform/issues/44) regarding proxy configuration and download of a tool not working. In the extension in question, I am still using the old `vsts-task-tool-lib`. In this lib, there is a method off the tools module named `downloadTool`. I noticed that this is respecting the Agent.Proxy* build variables to ensure the request uses the configured proxy. However, I do not see the same function available in the latest `azure-pipelines-task-lib'. **What is the appropriate module and function to use download tools that respects the configured proxy for the agent?** 

This is stopping me from updating my extension to the latest version

**Comment by damccorm** [comment]
I'm not 100% sure I understand the issue here, but I think you may be confusing this repo with the [azure-pipelines-tool-lib](https://github.com/Microsoft/azure-pipelines-tool-lib). When we rebranded the vsts-task-tool-lib became that library, while this library was originally the vsts-task-lib (its confusing I know).

So I think you sill want to use the tool-lib's [downloadTool](https://github.com/Microsoft/azure-pipelines-tool-lib/blob/2fa9e4ec35a9d59d589d5472da8b9af1b6aea6f2/tool.ts#L198) function. If that's not respecting the agent proxy, that's a bug, it should be I believe.

**Comment by charleszipp** [comment]
Thanks @damccorm. This gives me the info I needed. If I find any issues with the proxy configuration in the tools lib, I will follow up there. Thanks for your help!
