### ISSUE TITLE
ToolRunner quoted args are ignored

### ISSUE THREAD

**Issue by maciejmaciejewski** [microsoft/azure-pipelines-task-lib#520]
### Environment
Agent
FROM microsoft/vsts-agent:ubuntu-16.04-docker-17.12.0-ce-standard

Lib version
azure-pipelines-task-lib@2.8.0

### Issue Description
I am trying to run Lighthouse Audit executed via ToolRunner. The problem is that in order to run it on Unix based VSTS agent I have to pass multiple parameters with `chrome-flags`

Source code can be found here https://github.com/maciejmaciejewski/azure-pipelines-lighthouse/blob/master/task/src/execute-lighthouse.ts#L81

Full command is 
`/usr/local/bin/lighthouse http://example.com --output=html --output=json --output-path=/var/vsts/work/6/s/lighthouseresult --chrome-flags="--no-sandbox --headless --disable-gpu"` 

### Actual behaviour
As an output I get following error message `Running as root without --no-sandbox is not supported`

When I run this command manually on VSTS agent container it works properly.
This suggest that there is some issue with escaping quotes and space delimited arguments and its value is completely ingored.

Escaping it with backslash did not help at all, I was also trying double escaping, using single quotes and even backtick.

### Logs
```
##[debug]/usr/local/bin/lighthouse arg: ["http://example.com","--output=html","--output=json","--output-path=/var/vsts/work/6/s/lighthouseresult","--chrome-flags=\"--no-sandbox --headless --disable-gpu\""]
##[debug]evaluateAuditRules=false
##[debug]auditRulesStr=null
##[debug]exec tool: /usr/local/bin/lighthouse
##[debug]arguments:
##[debug]   http://example.com
##[debug]   --output=html
##[debug]   --output=json
##[debug]   --output-path=/var/vsts/work/6/s/lighthouseresult
##[debug]   --chrome-flags="--no-sandbox --headless --disable-gpu"
```

**Comment by damccorm** [comment]
I'll take a look. We need to think about how we're handling quotes in general (see #511)

**Comment by maciejmaciejewski** [comment]
Hello @damccorm thank you for your answer. 
I will modify `toolrunner.ts` locally and see if it helps.

**Comment by damccorm** [comment]
I'm struggling a little bit to see how it would have been failing before but succeeding with your replacement function. It looks to me like we're basicaly [calling the same thing](https://github.com/Microsoft/azure-pipelines-task-lib/blob/3fb907124e461cb7dc757200266d57f6ac743c8e/node/toolrunner.ts#L801).

We call `child.spawn(this._getSpawnFileName(), this._getSpawnArgs(optionsNonNull), this._getSpawnOptions(options));`

Due to the implementation of [`_getSpawnFileName`](https://github.com/Microsoft/azure-pipelines-task-lib/blob/3fb907124e461cb7dc757200266d57f6ac743c8e/node/toolrunner.ts#L208) and [`_getSpawnArgs`](https://github.com/Microsoft/azure-pipelines-task-lib/blob/3fb907124e461cb7dc757200266d57f6ac743c8e/node/toolrunner.ts#L218), this basically can be reduced to `child.spawn(this.toolPath, this.args, this._getSpawnOptions(options));`

This leaves [_getSpawnOptions](https://github.com/Microsoft/azure-pipelines-task-lib/blob/3fb907124e461cb7dc757200266d57f6ac743c8e/node/toolrunner.ts#L482) as the only thing that could be causing issues, but the only thing different there is that we drop the `shell` option - that doesn't seem like it would break this though (and I don't really see why this would be advantageous here). Did you change anything else here that might have caused this to now work?

**Comment by maciejmaciejewski** [comment]
Indeed the only difference between them are exec options, I used shell true because as far as I remember it did not work without it.
Yo can check my implementation details of [https://github.com/maciejmaciejewski/azure-pipelines-lighthouse/blob/master/task/src/execute-lighthouse.ts#L130](exec()) function.

**Comment by damccorm** [comment]
I'm going to close this since its consistent with how Node handles this. Feel free to comment if you'd like me to reopen
