### ISSUE TITLE
3.0.2 release or at least add ability to mock missing task lib functions in the stable version

### ISSUE THREAD

**Issue by praneetloke** [microsoft/azure-pipelines-task-lib#530]
### Environment
azure-pipelines-task-lib version: 2.8.0

### Issue Description
The stable version's `mock-answers` doesn't contain all of the functions of the task lib for mocking. It looks like the latest version in `master` v3.0.2 contains the `getPlatform`.

I see that npm has the 3.0.0-preview tag, but not the latest 3.0.2. If at least the 3.0.2-preview could be released, those who need to mock the missing functions would be unblocked.

Also, when would the v3.x be released as the latest stable version? As I mentioned in the title, it would be good to at least have this change in the stable 2.x version if 3.x has a long way to go to be stable?

**EDIT**: For now, I have chosen to use the deprecated `osType` function to get the platform label.

### Expected behaviour
Cannot mock `getPlatform` in the current stable version 2.8.0.

### Actual behaviour
Able to set the mock answer for `getPlatform` (and other functions of the task lib) using `mock-answer.TaskLibAnswers`.

### Steps to reproduce
N/A

### Logs
When running a test for a task that uses the `getPlatform` function, I get this:

```
##vso[task.issue type=error;]TypeError: tl.getPlatform is not a function
##vso[task.complete result=Failed;]TypeError: tl.getPlatform is not a function
```

**Comment by damccorm** [comment]
This is still a little up in the air, but I think that as of right now we're actually not going to major version (turns out the changes we want aren't going to be breaking after all). #531 should drop the version back down to 2.9.0 and we'll release.

One workaround for the moment is to clone the library and explicitly mock the `getPlatform` function and mock the library (see [here](https://github.com/Microsoft/azure-pipelines-tasks/blob/e36c173ca833ec27b39a8bd330ff6e9057da5446/Tasks/UseNodeV1/Tests/L0FirstDownloadSuccess.ts#L20) for an example of this). With that said, 2.9.0 should be released soon.

**Comment by praneetloke** [comment]
Thanks for the response, @damccorm. I'll wait for the 2.9.0. I'll close this issue once I am able to mock `getPlatform` in the new version successfully.

**Comment by damccorm** [comment]
Ok, sounds good, thanks for your patience

**Comment by damccorm** [comment]
> I'll close this issue once I am able to mock getPlatform in the new version successfully.

This has been fixed
