### ISSUE TITLE
Environment variable name converted to uppercase

### ISSUE THREAD

**Issue by Yiming-Jia** [microsoft/azure-pipelines-task-lib#534]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 
2.8.0
### Issue Description

call tl.setVariable, and variable name gets converted to upperCase.
### Expected behaviour

In linux environment, the environment variable name is case sensitive. Would customers expect case sensitive? 
### Actual behaviour

variable name gets converted to upperCase.
### Steps to reproduce
1. tl.setVariable("variablename", "value");
2. run powershell: gci env:* | sort-object name;
3. variable is: VARIABLENAME: value

**Comment by damccorm** [comment]
This is by design. We decided to make our variables case-insensitive.

To be honest, I'm not 100% sure what went into this decision originally, but I think at this point its not clear to me that we should be case sensitive and it definitely doesn't seem worth it to make a change that will break compat.

**Comment by stephenmichaelf** [comment]
Danny is correct, we don't plan to change sensitivity here.
