### ISSUE TITLE
Input names in YAML are case sensitive if they're service connections

### ISSUE THREAD

**Issue by vtbassmatt** [microsoft/azure-pipelines-task-lib#539]
Following up from https://github.com/microsoft/azure-pipelines-tasks/issues/10294 and https://github.com/MicrosoftDocs/vsts-docs/pull/4199

Input names in YAML should be case-insensitive. They mostly are, except if the type is a service connection. (I'm not 100% positive this is task-lib related, but it was the right place to start an investigation.)

**Comment by damccorm** [comment]
This is a weird error - I don't think its task-lib related, but I'm not 100% sure. Input names definitely are not case sensitive here - see [here](https://github.com/microsoft/azure-pipelines-task-lib/blob/2f33a98ba5ba53488286e0f4c5120e014193c91d/node/task.ts#L219) where we uppercase.

With that said, what is really throwing me off here is that in https://github.com/microsoft/azure-pipelines-tasks/issues/10294 they're actually successfully getting the input - in the logs it says `##[debug]gitHubConnection=02fca1fc-7627-4efd-8f21-73a5f1d82e54` which only gets logged as `getInput` is [about to return](https://github.com/microsoft/azure-pipelines-task-lib/blob/2f33a98ba5ba53488286e0f4c5120e014193c91d/node/task.ts#L228).

Normally I

**Comment by damccorm** [comment]
From the diagnostic log it looks like the endpoint we get from `getInput` is the same:

`##[debug]gitHubConnection=e52eaa22-feb4-4f41-bb9f-e15cc972dc98`

So that doesn't seem to be the issue. The function that gets called immediately after (and fails) is [getEndpointAuthorization](https://github.com/microsoft/azure-pipelines-task-lib/blob/bfddff3013b85ce9d9f534160d33a70e992eb9ed/node/task.ts#L375). Basically what this failing means is that `ENDPOINT_AUTH_E52EAA22-FEB4-4F41-BB9F-E15CC972DC98` isn't getting set and it should be. 

This almost definitely isn't a task-lib issue, but I'm not really sure where to route. It might be an agent issue? My sense is that something isn't getting passed to the agent correctly though. @TingluoHuang or @ericsciple might be able to route better though.
