### ISSUE TITLE
[Discussion] tl.getInput() and other similar methods to read task inputs should be able to expand linux macro's like '~', $HOME, etc

### ISSUE THREAD

**Issue by vineetmimrot** [microsoft/azure-pipelines-task-lib#547]
We have many linux based tasks and most of them uses tl.which(), tl.tool(), tl.tool().exec() instead of running under bash. So if user uses '~', $HOME and other linux macros in the task input then it will not get expanded to its actual value and it doesn't provide similar behavior when user run it locally.

IMO either i) tl.getInput() and other similar methods to read task inputs should be tweaked to return expanded value in case of running on linux agents 
or ii) there should be guideline that linux based task should only use bash.

Though their are cons for these strategies that it may break existing user scenarios. 
Please provide your inputs.

**Comment by vineetmimrot** [comment]
@sachinma For dotnetcorecli task and other linux based task we own/

**Comment by damccorm** [comment]
FYI, for anyone new to this conversation, see https://github.com/microsoft/azure-pipelines-tool-lib/issues/56 for previous discussion on this.

Looking at the 2 things suggested:

> i) tl.getInput() and other similar methods to read task inputs should be tweaked to return expanded value in case of running on linux agents

As mentioned in the other issue, this will break existing tasks. Additionally, it doesn't really make sense to me to automatically assume that any inputs are definitely meant to be used exactly as they would be on the terminal. So I don't think this is an option.

> ii) there should be guideline that linux based task should only use bash.

Not sure what you mean by this. Plenty of Linux based tasks use the task-lib without problem, so I don't _think_ this is true, but again I don't really understand what you're asking.

Seperately, I also want to point out that if you want arguments evaluated like the command line does, an easy way to do this is to just run a shell and call `echo ${arg}`. You can capture the output using the task-lib's execSync functionality. This is also pretty lightweight so I don't think you really need to worry about the overhead being costly.

All in all, while I agree the discussion probably belongs in this repo instead of the tool-lib I think the same logic applies here.

**Comment by damccorm** [comment]
I think we're not going to do this for the aforementioned reasons, most important being that this will break existing scenarios. It's also much heavier weight than what we supply and not clearly better to me.
