### ISSUE TITLE
Execute different task or execute PowerShell script

### ISSUE THREAD

**Issue by drauch** [microsoft/azure-pipelines-task-lib#551]
### Environment
azure-pipelines-task-lib version: 2.8.0

### Issue Description
I want to write a task which is a wrapper around our PowerShell module. The task should exist as a thin wrapper around it, so it can be used comfortably in Azure Pipelines.

Is it possible to call the PowerShell task from within our own task? If not, is there a way to execute a PowerShell script from within our task?

Our task is written in TypeScript as described here: https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task

Best regards,
D.R.

**Comment by drauch** [comment]
I've seen that there is a PowerShell SDK (https://github.com/microsoft/azure-pipelines-task-lib/blob/master/powershell/Docs/README.md), but I want to execute a PowerShell-core compatible one which runs on Win/Linux/Mac.

**Comment by damccorm** [comment]
No, the powershell handler will still be restricted to Windows. Right now we don't offer a PowerShell core handler, that's an enhancement we're looking at though, see #314 where this is being tracked.

I'm going to close here since your original question has been answered and the PowerShell core question is being tracked elsewhere

**Comment by drauch** [comment]
#314 is locked - is this a mistake or on purpose?
