### ISSUE TITLE
remove .taskkey file from my task

### ISSUE THREAD

**Issue by gforceg** [microsoft/azure-pipelines-task-lib#556]
### Environment
azure-pipelines-task-lib version: 2.8.0

### Issue Description

I created a vsts task (typescript) and my org is looking at open sourcing it. A '.taskkey' file containing a GUID made its way into my git repo and I'm sure it doesn't belong there.

Is this file a secret that needs to be purged from the history of my git repo? Or can I just delete + ignore it going forward?

**Comment by damccorm** [comment]
This would've been only created while testing the task, not during the actual execution from within the context of the agent. So basically, if you were using real secrets somehow while testing (which seems unlikely), you would want to be careful about exposing it, but otherwise it should be fine.

As a side note, I'm surprised that happened. A couple questions - (1) Were you previously consuming an older version of the task-lib in this task? (2) If you do open source the task, could you share it here? I'd be interested in taking a look into why this happened.

**Comment by gforceg** [comment]
1. I don't think so but I did fork the repository off of a much older task purely to avoid recreating readme / task.json files. The original repo was written in powershell. There was no package.json or node_modules, only a ps_modules/VstsTaskSdk directory. After I forked the project I blew away all files / directories except for task.json and README.md. Then I just followed the tutorial linked in the [Azure Pipeline Tasks README](https://github.com/microsoft/azure-pipelines-tasks/blob/master/README.md) because I wanted to learn how to add unit tests. The task uses azure-pipelines-task-lib@^2.8.0.

2. Sure!
