### ISSUE TITLE
ToolRunner should provide a interface to clear the value of args

### ISSUE THREAD

**Issue by Bae984** [microsoft/azure-pipelines-task-lib#561]
### Environment
azure-pipelines-task-lib version: 2.8.0

### Issue Description
There is no problem. But in my scenario, I wanna repeat to use a ToolRunner object with different args. Currently, ToolRunner only supports appending arguments to variable args via method line() or args(). I have no way to clear these arguments I set before. I think We all agree that it's unnecessary to create multiple ToolRunner objects with same toolpath but different args for efficiency. And I wonder that is there another better solution to do what I ask now rather than using multiple ToolRunner objects?

### Expected behaviour
Provide a interface to clear the value of args.
Or Provide a alternative solution to use multiple ToolRunner objects with same toolpath but different args.

Looking forward to reply, thanks!

**Comment by BethanyZhou** [comment]
Let me know what you think please.

**Comment by reillysiemens** [comment]
I don't know if providing a method to clear `this.args` on the `ToolRunner` is the right call, but I do find the current interface cumbersome.

Right now, unless I'm mistaken, to execute multiple calls to the same tool you need to write something like.
```typescript
const gitInit = tl.tool("git").arg(["init", "."]);
const gitStatus = tl.tool("git").arg(["status"]);
gitInit.execSync();
gitStatus.execSync();
```

It might feel more intuitive to write something like

```typescript
const git = tl.tool("git");
git.arg(["init", "."]).execSync();
git.arg(["status"]).execSync();
```

but this causes an error right now because arguments are retained in the `args` array, so the second call ends up being
```typescript
["init", ".", "status"]
```
This might be helpful in some use cases, but is quite unhelpful for others.

The confusion could be a result of the naming for the `tool` function. What you get after calling `tool` is not a multi-use `Tool`, but a single-use `ToolRunner` and the distinction is important.

In subsequent major versions I think it could be worth revisiting this interface for improved ergonomics. At the very least, I don't see clear, accessible documentation to help guide people away from this pitfall.
