### ISSUE TITLE
Old tasks are being pointed here for deprecated tasks and there is nothing addressing it

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/azure-pipelines-task-lib#562]
# Issue Description
Old tasks are getting the warning message 

```
##[warning]Task [XXXX] is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
```

but I can't find any docs that talk about the upgrade process.

### Expected behaviour

A wiki or docs page should be created that walks through the process of upgrading the task-lib.

### Actual behaviour

There are some tutorials on how to create _new_ tasks.

### Logs

Specifically, I ran into this because I wanted to help out on https://github.com/sergeyzwezdin/magic-chunks, but I don't see a task-lib or anything similar being used anywhere.

**Comment by AlysterS** [comment]
Seeing this warning appear in the **Send Email** task. Will these tasks be updated in the near future or is there a way to correct this within an Azure DevOps Service instance manually?

### Warning Message
`##[warning]Task 'SendEmail' (1.1.1029) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib`

**Comment by damccorm** [comment]
Hi, these tasks are 3rd party tasks, so we can't speak into whether they'll be updated or not.

@MisinformedDNA I can't really tell what's going on in that task, but it looks like its mostly just running a powershell script - you should just be able to use this libraries powershell lib to get inputs and execute the script as if you were starting from scratch. Some good examples of powershell tasks can be found in https://github.com/microsoft/azure-pipelines-tasks (a good example is [AzurePowerShell](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzurePowerShellV2)), though in general our recommendation would be to upgrade to a node task using the new tasks docs so that you get full cross platform support

**Comment by damccorm** [comment]
Closing since I think this is a no-op on our end with 3rd party tasks.
