### ISSUE TITLE
azure-pipelines-task-lib wrapped parameter by " on ubuntu agent

### ISSUE THREAD

**Issue by blackchoey** [microsoft/azure-pipelines-task-lib#577]
### Environment
azure-pipelines-task-lib version: ^2.8.0

### Issue Description

We received customer report that azure-pipelines-task-lib wrapped parameter by `"` on ubuntu agent. We're using task.exec function to execute Azure CLI commands and passed the parameters as array. This happened starting from 9/25. For example, one parameter passed to Azure Pipelines task is `tags.a='amd64' and tags.b='true' and tags.c='somevalue'`

### Expected behaviour

The parameter in Azure CLI command is wrapped by `"` on ubuntu agent: `"tags.a='amd64' and tags.b='true' and tags.c='somevalue'"`
### Actual behaviour

The parameter in Azure CLI command should not be wrapped by `"` on ubuntu agent: `tags.a='amd64' and tags.b='true' and tags.c='somevalue'`

**Comment by stephenmichaelf** [comment]
@damccorm Can you take a look at this?

**Comment by damccorm** [comment]
Hey @blackchoey, this looks like an issue with the Azure CLI task itself. Would you mind filing the issue on the task here - https://github.com/microsoft/azure-pipelines-tasks/issues/new? That way it can get routed to the correct owners. I'm going to close here since this isn't an issue with the task-lib
