### ISSUE TITLE
Task execution target file can no longer be outside of root directory when using PowerShell3 task execution handler

### ISSUE THREAD

**Issue by deadlydog** [microsoft/azure-pipelines-task-lib#601]
### Environment
azure-pipelines-task-lib version: VstsTaskSdk.psm1 version 0.11.0

### Issue Description
The `target` command does not allow the task execution target file to be outside of the task's root directory when using the `PowerShell3` task execution handler.

### Expected behaviour
We expect the task execution target file to get invoked.

### Actual behaviour
An error message saying the task execution target file cannot be found is thrown.

### Steps to reproduce
1. Create a task that uses the `PowerShell3` task execution handler.
2. In the `task.json`'s `target` command, specify a path to the task execution target file that is in a different directory.
e.g. 
```json
  "execution": {
    "PowerShell3": {
      "target": "$(currentDirectory)/Code/Wait.ps1",
      "workingDirectory": "$(currentDirectory)"
    }
  }
```

### Logs
More details including file structure and output can be found [in this StackOverflow question](https://stackoverflow.com/questions/58527792/azure-devops-custom-build-task-extension-cannot-find-powershell-vststasksdk-psd1). I thought this was maybe intended behaviour and proposed updates to the documentation in #582 but it was determined this is a bug in the software.

**Comment by deadlydog** [comment]
Reading through the answer on the Stack Overflow post, perhaps the issue is not that the task execution target file needs to be in the root directory, but that the SDK `ps_modules` directory needs to be in the same directory as the task execution target file (Wait.ps1 in the example given above). If that's the case, then perhaps the documentation could just be updated to say that. Currently [the docs](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/powershell/Docs/Consuming.md) say:

> The ps_modules folder should be in the root of the task folder.

**Comment by damccorm** [comment]
I think that's right. Technically, its not impossible for them to be at different levels, but I agree that its simplest for them to be at the same level, and that's what we should be recommending. Right now, if you follow the recommended path this will actually work because we do recommend putting the script at the root (mostly I think because its easier to reason about things) - https://github.com/microsoft/azure-pipelines-task-lib/blob/master/powershell/Docs/Consuming.md#taskjson-modifications - but I think it would be good to change the wording a little bit in case people don't follow that for whatever reason. I've added #602 to clarify

**Comment by deadlydog** [comment]
Awesome, thanks @damccorm . For myself, I was migrating my extension from a regular PowerShell execution handler to a PowerShell3 execution handler, and originally I had all of my "business logic" code separated from the "extension infrastructure" code by placing it in it's own directory. That's what led me to falling into this scenario. Thanks for updating the docs!
