### ISSUE TITLE
mkdirP may fail if a concurent job is creating same directory structure in parallel

### ISSUE THREAD

**Issue by williambernardet** [microsoft/azure-pipelines-task-lib#606]
One of our build is using the Publish build artifacts task, and fails creating the target directory with the following error message:
Unable to create directory `'\\server\Release\product\refs\pull\54113\merge\20200115.12\8.0.128\Logs_DEBUG_DEFAULT'. EEXIST: file already exists, mkdir '\\server\Release\product\refs\pull\54113\merge\20200115.12'
`

The task seems to use the following code to create recursively the directory structure:
https://github.com/microsoft/azure-pipelines-task-lib/blob/f3d9507949d1b903a2829ed5f4ec084098e78899/node/task.ts#L705

The catch close should check if the error code is actually EEXIST, and then skip the exception trying to create next part of the path.

**Comment by damccorm** [comment]
Honestly, at this point we should probably just be shelling out to node's built in function - https://nodejs.org/api/fs.html#fs_fs_mkdirsync_path_options

They didn't initially have the recursive option which is why this function existed, but there's not really a need for it anymore - I'd probably actually recommend just using that directly - we'll keep this one for back compat but probably update it to just call that (unless I'm missing something)

**Comment by damccorm** [comment]
Oh wait, I immediately take that back - we need to be able to run on node 6 so we can't count on functions added in node 10 :/

**Comment by damccorm** [comment]
I think I agree this is a good change - @williambernardet do you want to open a PR for this one? If not I'm happy to take it
