### ISSUE TITLE
Get AzureDevOps Server version via the extension

### ISSUE THREAD

**Issue by knowds** [microsoft/azure-pipelines-task-lib#636]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: AzureDevOps extension

### Issue Description
Need to fetch the AzureDevOps server version in the extension

### Expected behaviour
Should be able to report the AzureDevOps server version, the extension is integrated with

### Actual behaviour
Unable to find a library to achieve the desired output.

**Comment by damccorm** [comment]
Hey @knowds - the server itself doesn't currently output this info as far as I know. Since we're just a wrapper for tasks, we don't have the ability to surface that information in this library. Since its a more general service issue, please open this request at https://developercommunity.visualstudio.com/spaces/21/index.html.

FWIW I'd guess we probably won't be able to do this in a particularly helpful way since it would require patching all existing versions of AzureDevOps and forcing existing customers to upgrade (which is something we never do). One option you have here that would get around this requirement is to take the version as an input.
