### ISSUE TITLE
Vulnarable dependency used: string_decoder 1.1.1

### ISSUE THREAD

**Issue by erkib** [microsoft/azure-pipelines-task-lib#907]
### Environment
azure-pipelines-task-lib version: 4.1.0

### Issue Description
Vulnerable dependecy found: string_decoder 1.1.1

azure-pipelines-task-lib [4.1.0]
sync-request [6.1.0] -> this is the latest version of this package, 4 years old. There is big bold remark - "Do not use for production"
then-request [6.0.0] -> 6.0.2 is the latest, 4 years old
concat-stream [1.6.2] -> 2.0.0 is the latest, 4 years old
readable-stream [2.2.2] -> 4.2.0 is the latest, 2 months old
stream_decoder [1.1.1] -> 1.3.0 is the latest, 3 years old

**Comment by DenisRumyantsev** [comment]
@erkib thanks for reporting this issue, we will work on it

**Comment by vmapetr** [comment]
Hi, @erkib! 
Thank you for the report! The following packages here except for _sync-request_ and _then-request_ don't have direct vulnerabilities, but updating them to the latest versions will be considered a breaking change, so it's preferable to leave the current versions for now.
Regarding the _sync-request_ package - it cannot be actually considered as a production usage here, because it is used only in tests, however, we have plans for replacing it for the async package in the future.

**Comment by vmapetr** [comment]
I'm going to close this issue, please feel free to reopen it if you have any concerns.
