### ISSUE TITLE
CVE-2022-37614 in mockery 2.1.0

### ISSUE THREAD

**Issue by joshftb** [microsoft/azure-pipelines-task-lib#933]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 4.3.1

### Issue Description

[There is a prototype pollution bug in mockery, a prod dependency](https://nvd.nist.gov/vuln/detail/CVE-2022-37614)
[package.json here](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/package.json#L31)
### Expected behaviour

n/a
### Actual behaviour

n/a
### Steps to reproduce
1. Run component governance on pipeline

**Comment by mikeharder** [comment]
This is also blocking us.

Should `mockery` be a `devDependency` instead of `dependency`?  It appears to be only used for testing.

**Comment by DenisRumyantsev** [comment]
@joshftb @mikeharder thanks for reporting! We are working on this

**Comment by revisited-18** [comment]
Hi @DenisRumyantsev , @LiliaSabitova , is there any update on this? This is blocking us as well.

**Comment by ronrcruz** [comment]
@LiliaSabitova any updates? im blocked and my builds are gonna break soon

**Comment by revisited-18** [comment]
@LiliaSabitova  any updates? This is blocking us and has also made our S360 dashboards Red.

**Comment by LiliaSabitova** [comment]
We're planning to replace "mockery" package with another one, most probably "sinon".
But it will take some time, because of the existing dependencies to "mockery" package.

Actually, we don't use the vulnerable function of "mockery" and to unblock you, you can just dismiss the alert.
Go to the Compliance -> Component Governance for your project, select affected repo and CG alert, and select dismiss. Set the reason to "Identified vulnerable method is not used":

![image](https://github.com/microsoft/azure-pipelines-task-lib/assets/107196662/7f85ad68-41d2-4ecc-9a91-4242ccb98457)
![image](https://github.com/microsoft/azure-pipelines-task-lib/assets/107196662/dd2a88b1-ceb5-4630-9384-2017dfe34338)
![image](https://github.com/microsoft/azure-pipelines-task-lib/assets/107196662/b9ab1bf7-50a5-41a8-aade-1b5892c2ba66)

**Comment by pramodc0777** [comment]
@LiliaSabitova  is there any timeline for replacing mockery as this is blocking us from using azure pipeline task , it needs to be fixed , please comment on timeline when it will be available.

**Comment by joshftb** [comment]
> @LiliaSabitova is there any timeline for replacing mockery as this is blocking us from using azure pipeline task , it needs to be fixed , please comment on timeline when it will be available.

@pramodc0777, mockery is only used for testing, so none of its exports will see prod. Also, the task does not use the vulnerable component of that library anyways.
